[package]
name = "walked"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
